stages:
  - build
  - push

# Variables globales (fournies automatiquement par GitLab)
variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: latest

# =========================
# JOB 1 : BUILD IMAGE
# =========================
build_image:
  stage: build
  image: docker:25
  services:
    - docker:25-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
  only:
    - main

# =========================
# JOB 2 : PUSH IMAGE
# =========================
push_image:
  stage: push
  image: docker:25
  services:
    - docker:25-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main
